<?php
class Controller_User extends Controller
{
    function action_logout(){
        //Model_User::logout();
        session_destroy();
        setcookie("PHPSESSID", "", time() - 3600, "/");
        header("Location:http://mstk.com");
    }
    function action_auth(){
        if(Model_User::auth($_POST)) {
            $_SESSION['permissions'] = Model_ACL::get_permissions($_SESSION['role']);
            header("Location:http://mstk.com/major");
        }
        else{
            header("Location:http://mstk.com");
        }
    }

    function action_send_mail()
    {
        $to = $_SESSION['email'];
        $to='andrej.mitryakov@yandex.ru';//to delete
        $subject = 'Finish your signing up on mstk.com';
        $message = 'This is autogenerated link, don\'t click on it if you didn\'t sign up. http://mstk.com/major/finish/'.$_SESSION['url'];
        $from = 'From:no-reply@gmail.com';
        mail($to, $subject, $message, $from);
        header("Location:http://mstk.com");
    }

    function action_add_user()
    {
        //session_start();
        Model_User::add_user($_POST);
        Model_Stockage::add_potential_user();
        header("Location:http://mstk.com/user/send_mail");
        //header('Location: ' . $_SERVER['HTTP_REFERER']);
        //header("Location:http://mstk.com");
    }
    function action_get_users()
    {
        //$result = Model_User::get_all_users($_POST);
        //header("Location:http://mstk.com/major/users");
        echo " PROBLEM IS SOMEWHERE HERE";
        exit();
        
    }
    function action_delete_user()
    {
        Model_User::delete_user($_POST['id']);
        header('Location: ' . $_SERVER['HTTP_REFERER']);
    }
    function action_change_role()
    {
        Model_User::change_role($_POST);
        header('Location: ' . $_SERVER['HTTP_REFERER']);
    }
    function action_get_role()
    {
        $result = Model_User::get_role($_POST);
        header('Location: ' . $_SERVER['HTTP_REFERER']);
    }
    function action_index()
    {
        
    }
    function action_registration()
    {
        
    }
}